baseURL = "https://blog.air1.cn/"
title = "Air1"
theme = "air1"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
relativeURLs = true
enableRobotsTXT = true
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Air1，个人博客。不定期更新。"
  copyright = "© 2026 Air1"
  dark = "auto"
  highlight = true
  siteAuthor = "Air1"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "post"
    title = "post"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[pagination]
  pagerSize = 10

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  ordered = true
